/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinejohan;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;


public class windowCentral extends javax.swing.JFrame {
    connection conection = new connection();
    roomCine roomPrimary = new roomCine();
    roomCine roomSecundary = new roomCine();
    public windowCentral() {
        initComponents();
        this.conection.conectar();
        
        
        roomPrimary.setCapacity(500);
        roomPrimary.setEntryPrice(8.0);
        
        roomSecundary.setCapacity(300);
        roomSecundary.setEntryPrice(6.0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labTitlePrimary = new javax.swing.JLabel();
        labMovie = new javax.swing.JLabel();
        TextFieldMovie = new javax.swing.JTextField();
        buttonChangesPrincipal = new javax.swing.JButton();
        buttonNewSell = new javax.swing.JButton();
        buttonOcupation = new javax.swing.JButton();
        buttonEmpty = new javax.swing.JButton();
        buttonIncome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinejohan/johan.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labTitlePrimary.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labTitlePrimary.setText("Room Principal");

        labMovie.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        labMovie.setText("Movie");

        TextFieldMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldMovieActionPerformed(evt);
            }
        });

        buttonChangesPrincipal.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        buttonChangesPrincipal.setText("CHANGES");
        buttonChangesPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangesPrincipalActionPerformed(evt);
            }
        });

        buttonNewSell.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        buttonNewSell.setText("NEW SELL");
        buttonNewSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewSellActionPerformed(evt);
            }
        });

        buttonOcupation.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        buttonOcupation.setText("% OCUPATION");
        buttonOcupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOcupationActionPerformed(evt);
            }
        });

        buttonEmpty.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        buttonEmpty.setText("EMPTY");
        buttonEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmptyActionPerformed(evt);
            }
        });

        buttonIncome.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        buttonIncome.setText("INCOME");
        buttonIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labTitlePrimary)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonNewSell)
                                .addGap(18, 18, 18)
                                .addComponent(buttonOcupation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonEmpty))
                            .addComponent(TextFieldMovie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonIncome)
                            .addComponent(buttonChangesPrincipal))
                        .addContainerGap(98, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitlePrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonChangesPrincipal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewSell)
                    .addComponent(buttonOcupation)
                    .addComponent(buttonEmpty)
                    .addComponent(buttonIncome))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 590, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinejohan/johan.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 610, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void buttonOcupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOcupationActionPerformed
        String info;
        info = "Room Central\n";
        info += "Movie : "+roomPrimary.getTitleMovie()+"\n";
        info += "Capacity : "+roomPrimary.getCapacity()+"\n";
        info += "Seat busy : "+roomPrimary.getSeatBusy()+"\n";
        info += "Seat free : "+roomPrimary.getFree()+"\n";
        info += "Parcentage : "+roomPrimary.getPorcentaje()+"\n";
        JOptionPane.showMessageDialog(null,  info);
    }//GEN-LAST:event_buttonOcupationActionPerformed

    private void buttonNewSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewSellActionPerformed
        roomPrimary.entraUno();
    }//GEN-LAST:event_buttonNewSellActionPerformed

    private void buttonChangesPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangesPrincipalActionPerformed
        String title;
        title= JOptionPane.showInputDialog(null, "Enter the title of one movie : ");
        roomPrimary.setTitleMovie(title);
        TextFieldMovie.setText(title);
    }//GEN-LAST:event_buttonChangesPrincipalActionPerformed

    private void TextFieldMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldMovieActionPerformed

    }//GEN-LAST:event_TextFieldMovieActionPerformed

    private void buttonEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmptyActionPerformed
        roomPrimary.vaciar();
        TextFieldMovie.setText("");
    }//GEN-LAST:event_buttonEmptyActionPerformed

    private void buttonIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncomeActionPerformed
        String info;
        info = "Incomes of the movie "+roomPrimary.getIncomes()+"Euros";
        JOptionPane.showMessageDialog(null, info);        
    }//GEN-LAST:event_buttonIncomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(windowCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(windowCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(windowCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windowCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new windowCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldMovie;
    private javax.swing.JButton buttonChangesPrincipal;
    private javax.swing.JButton buttonEmpty;
    private javax.swing.JButton buttonIncome;
    private javax.swing.JButton buttonNewSell;
    private javax.swing.JButton buttonOcupation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labMovie;
    private javax.swing.JLabel labTitlePrimary;
    // End of variables declaration//GEN-END:variables
}
